meta:
  engine: 4.1.0
  version: 0.0.0
  author: philipsoitu
units:
  # choc sized switches
  kx: cx
  ky: cy
  # padding + 2mm
  px: kx + 2
  py: ky + 2
  # mm
  offset: 0
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        outer:
        pinky:
          key.stagger: 2

        ring:
          key.stagger: 2
        middle:
          key.stagger: 2
        index:
          key.stagger: -2
        inner:
          key.stagger: -2
      rows:
        bottom:
        home:
        top:
        num:
    left-thumb-lower:
      key:
        padding: 1ky
        spread: 1kx
      columns:
        left:
          rows.top.skip: true
        mid:
          rows.top.skip: true
          key.stagger: -2
      rows:
        bottom:
          shift: [3.5kx, -1ky]
    left-thumb-upper:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        shift: [6kx, -1ky]
      columns:
        right:
          key.splay: -15
      rows:
        bottom:
        top:
  mirror: &mirror
    ref: matrix_inner_num
    distance: 4.5kx
outlines:
pcbs:
cases:
